name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LOG_LEVEL: debug
          # optional
          LANGUAGE: Chinese
          PROMPT: "As a code review expert, please clearly point out the problems and suggestions of the code in a bullet-point list, and finally give a quality score from 1 to 100."
          IGNORE_PATTERNS: /node_modules,*.md # Regex pattern to ignore files, separated by comma
